#!/usr/bin/env python3
"""Sync homepage countdown data from timeline.html.

Writes js/countdown-deadlines.js and ensures index.html loads it before countdown.js.
Run this after changing registration deadlines in timeline.html.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime
from pathlib import Path

MONTHS = {
    "jan": 1,
    "feb": 2,
    "mar": 3,
    "apr": 4,
    "may": 5,
    "jun": 6,
    "jul": 7,
    "aug": 8,
    "sep": 9,
    "oct": 10,
    "nov": 11,
    "dec": 12,
}

DEADLINE_ORDER = ("early-bird", "regular", "late-bird")

DEADLINE_PATTERN = re.compile(
    r"<li><strong>(\d{1,2})\s+(\w{3})</strong>\s*—\s*"
    r"(Early bird|Regular|Late bird)\s+registration deadline</li>",
    re.IGNORECASE,
)

YEAR_PATTERN = re.compile(r"\b(20\d{2})\b")

INLINE_COUNTDOWN_PATTERN = re.compile(
    r"\n/\* Countdown \*/\n"
    r"const target = new Date\('[^']+'\);\n"
    r"function updateCountdown\(\) \{.*?\nsetInterval\(updateCountdown, 1000\);\n\n",
    re.DOTALL,
)

DEADLINES_SCRIPT_PATTERN = re.compile(
    r'<script src="js/countdown-deadlines\.js"></script>\n'
)


def infer_year(timeline_text: str) -> int:
    matches = YEAR_PATTERN.findall(timeline_text)
    if not matches:
        return datetime.now().year
    return int(max(matches, key=lambda y: matches.count(y)))


def parse_deadline(day: int, month_abbr: str, label: str, year: int) -> dict:
    month = MONTHS[month_abbr.lower()[:3]]
    key = label.lower().replace(" ", "-")
    date = datetime(year, month, day)
    title = f"{label.title()} Registration Deadline"
    return {
        "key": key,
        "label": label,
        "title": title,
        "date": date,
        "iso": date.strftime("%Y-%m-%d"),
    }


def load_deadlines(timeline_path: Path) -> list[dict]:
    text = timeline_path.read_text(encoding="utf-8")
    year = infer_year(text)
    deadlines = [
        parse_deadline(int(day), month, label, year)
        for day, month, label in DEADLINE_PATTERN.findall(text)
    ]
    if not deadlines:
        raise ValueError(f"No registration deadlines found in {timeline_path}")
    return sorted(deadlines, key=lambda item: item["date"])


def pick_deadline(deadlines: list[dict], forced: str | None, now: datetime | None = None) -> dict:
    if forced:
        forced_key = forced.lower()
        for item in deadlines:
            if item["key"] == forced_key:
                return item
        known = ", ".join(item["key"] for item in deadlines)
        raise ValueError(f"Unknown deadline {forced!r}. Expected one of: {known}")

    now = now or datetime.now()
    today = now.replace(hour=0, minute=0, second=0, microsecond=0)
    upcoming = [item for item in deadlines if item["date"] >= today]
    return upcoming[0] if upcoming else deadlines[-1]


def write_deadlines_js(deadlines_path: Path, deadlines: list[dict]) -> None:
    payload = [{"iso": item["iso"], "title": item["title"]} for item in deadlines]
    content = (
        "/* Generated by scripts/update-countdown.py — do not edit manually */\n"
        f"window.COUNTDOWN_DEADLINES = {json.dumps(payload, indent=4)};\n"
    )
    deadlines_path.write_text(content, encoding="utf-8")


def update_index(index_path: Path) -> bool:
    text = index_path.read_text(encoding="utf-8")
    updated = INLINE_COUNTDOWN_PATTERN.sub("\n", text)

    if '<script src="js/countdown.js"></script>' in updated:
        if not DEADLINES_SCRIPT_PATTERN.search(updated):
            updated = updated.replace(
                '<script src="js/countdown.js"></script>',
                '<script src="js/countdown-deadlines.js"></script>\n'
                '<script src="js/countdown.js"></script>',
                1,
            )

    changed = updated != text
    if changed:
        index_path.write_text(updated, encoding="utf-8")
    return changed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Sync homepage countdown data from timeline.html.",
    )
    parser.add_argument(
        "repo",
        nargs="?",
        default=".",
        help="Path to site repo (default: current directory)",
    )
    parser.add_argument(
        "--deadline",
        choices=DEADLINE_ORDER,
        help="Show which deadline is active; does not change generated data",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="List deadlines found in timeline.html and exit",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print actions without writing files",
    )
    args = parser.parse_args(argv)

    repo = Path(args.repo).resolve()
    timeline_path = repo / "timeline.html"
    index_path = repo / "index.html"
    deadlines_path = repo / "js/countdown-deadlines.js"

    if not timeline_path.is_file():
        parser.error(f"Missing timeline file: {timeline_path}")
    if not index_path.is_file():
        parser.error(f"Missing index file: {index_path}")

    deadlines = load_deadlines(timeline_path)
    selected = pick_deadline(deadlines, args.deadline)

    if args.list:
        for item in deadlines:
            marker = "  <- active" if item["key"] == selected["key"] else ""
            print(f"{item['iso']}  {item['title']}{marker}")
        return 0

    print(f"Active deadline: {selected['iso']} ({selected['title']})")

    if args.dry_run:
        print(f"Would write {deadlines_path}")
        print(f"Would update {index_path}")
        return 0

    deadlines_path.parent.mkdir(parents=True, exist_ok=True)
    write_deadlines_js(deadlines_path, deadlines)
    index_changed = update_index(index_path)

    print(f"Wrote {deadlines_path}")
    if index_changed:
        print(f"Updated {index_path}")
    else:
        print(f"No index changes needed in {index_path}")

    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except ValueError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc
